services:
  postgres:
    image: postgres:16-alpine
    container_name: file_postgres
    environment:
      POSTGRES_DB: file_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # Пароль postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d file_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: file_redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # ВАЖНО: Внутри докера рекламируем имя хоста "kafka", а не "localhost"
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

  minio:
    image: minio/minio
    container_name: file_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"

  upload-service:
    build:
      context: ./uploadService # Убедись, что папка называется именно так
    container_name: upload_service
    ports:
      - "8081:8081"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/file_db
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - APP_UPLOAD_TEMP_PATH=/tmp/file-uploader/uploads
    volumes:
      - shared_uploads:/tmp/file-uploader/uploads
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  processing-service:
    build:
      context: ./processingService # Убедись, что папка называется именно так
    container_name: processing_service
    ports:
      - "8082:8082"
    environment:
      # Kafka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

      # База данных (нужна для обновления статуса)
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/file_db
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres

      # MinIO (настройки подключения)
      # Внутри докера обращаемся к контейнеру "minio", а не "localhost"
      - APP_MINIO_ENDPOINT=http://minio:9000
      - APP_MINIO_ACCESS_KEY=admin
      - APP_MINIO_SECRET_KEY=password
      - APP_MINIO_BUCKET=uploads

      # Путь к файлам
      - APP_UPLOAD_TEMP_PATH=/tmp/file-uploader/uploads
    volumes:
      - shared_uploads:/tmp/file-uploader/uploads
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      minio:
        condition: service_started

volumes:
  shared_uploads: