server:
  port: 8081 # Порт первого микросервиса

spring:
  application:
    name: upload-service

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/file_db
    username: user
    password: password

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  codec:
    max-in-memory-size: 512KB

app:
  upload:
    temp-path: /tmp/file-uploader/uploads

    idempotency-ttl: 86400